export {default as NavBar} from './Navbars/Navbar'; 
export {default as NavBarForms } from './Navbars/NavbarForms';
export {default as NavBarTop } from './Navbars/NavbarTop';
export {default as SignUpForm} from './Forms/SignUpForm';
export {default as SignInForm} from './Forms/SignInForm';
export {default as LostPage }from './404';
export {default as Notification} from './Notification';
export {default as AuthButtons} from './Buttons/AuthButtons';
export {default as BoxContentPost} from './BoxContentPost';
export {default as LoadingHome} from './Loadings/LaoadingHome';
export {default as LoadingPage } from './Loadings/LoadingPage';